name: Scheduled Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.LOGIN_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'su-res'
          git config --global user.email 'suresh.subedi.3000@gmail.com'

      - name: Create and Commit File
        run: |
          echo "Daily commit on $(date)" > commit.txt
          git add commit.txt
          git commit -m "Auto commit on $(date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.LOGIN_TOKEN }}
